# Generated by Django 5.2.8 on 2025-11-26 03:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
                ('unidad', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio_base', models.IntegerField()),
                ('imagen_1', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen_2', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen_3', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('destacado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('contacto_cliente', models.CharField(help_text='Número de teléfono o correo electrónico', max_length=100)),
                ('descripcion_solicitud', models.TextField()),
                ('imagen_referencia', models.ImageField(blank=True, null=True, upload_to='pedidos_refs/')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_necesaria', models.DateField(blank=True, null=True)),
                ('plataforma', models.CharField(choices=[('FB', 'Facebook'), ('IG', 'Instagram'), ('WA', 'Whatsapp'), ('PR', 'Presencial'), ('WEB', 'Sitio Web'), ('OT', 'Otro')], default='WEB', max_length=3)),
                ('estado', models.CharField(choices=[('SOL', 'Solicitado'), ('APR', 'Aprobado'), ('PRO', 'En Proceso'), ('REA', 'Realizada'), ('ENT', 'Entregada'), ('FIN', 'Finalizada'), ('CAN', 'Cancelada')], default='SOL', max_length=3)),
                ('estado_pago', models.CharField(choices=[('PEN', 'Pendiente'), ('PAR', 'Parcial'), ('PAG', 'Pagado')], default='PEN', max_length=3)),
                ('token_seguimiento', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('producto_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.producto')),
            ],
        ),
    ]
